### ISSUE TITLE
Protocol fees calculated into input reserves update

### ISSUE THREAD

**Issue by janfabian** [skip-mev/bots#5]
Swap fees are sum of LP fee and protocol fee. The protocol fee part is sent to a protocol address and is not absorbed into LP.

Therefore the amount which is added to the reserves after swap should not contain the protocol fee. https://github.com/skip-mev/bots/blob/main/juno-arb/calculate.py#L31

(In case of junoswap `pass_through_swap` is the protocol fee for the first swap sent back to the user, the second swap goes to the junoswap)

**Comment by NotJeremyLiu** [comment]
Hey @janfabian ! Thanks for bringing this up. This is being addressed in v2: https://github.com/skip-mev/bots/blob/v2/cyclic-arbitrage/calculate.py#L5

If you want to test it out, top of v2 branch should be runnable by changing envs, but alley_oop branch is the most up to date and will be the completed refactor for v2

**Comment by janfabian** [comment]
👍 looking forward V2, great job
